cc_test(
    name = "opencv_build_test",
    size = "small",
    srcs = ["opencv_build_test.cc"],
    data = ["//src/testdata:images"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@opencv-bazel//:opencv",
    ],
)
