name: clang-checks

on:
  push:
    branches:
    - main
    # For easier development without having to push to main.
    - workspace-configuration

  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest

    name: "Clang checks"

    steps:
    - name: Prepare
      run: |
        sudo apt-get update -qq
        curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash /dev/stdin 18
        sudo apt-get install clang-tools-18 clang-format-18

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Formatting
      run: |
        FILES=$(mktemp)
        find ./src -regextype egrep -regex ".*[.](cc|h)" -print0 > "$FILES"
        xargs --null clang-format-18 --dry-run -Werror -- < "$FILES"

    - name: Clang Tidy
      run: |
        FILES=$(mktemp)
        find ./src -regextype egrep -regex ".*[.](cc|h)" -print0 > "$FILES"
        xargs --null clang-check-18 < "$FILES"
