name: Presubmit

on:
  push:
    branches:
    - main

  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-24.04

    name: "Build, Test, and Lint"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore bazel cache
      id: restore-bazel-cache
      uses: actions/cache/restore@v4
      with:
        path: "/home/runner/.cache/bazel"
        key: ${{ runner.os }}-bazelcache

    - name: Build
      run: bazel build --config=test //...

    - name: Save bazel cache
      id: save-bazel-cache-post-build
      uses: actions/cache/save@v4
      with:
        path: "/home/runner/.cache/bazel"
        key: ${{ runner.os }}-bazelcache

    - name: Test
      run: bazel test --config=test --test_output=errors //...

    - name: Save bazel cache
      id: save-bazel-cache-post-test
      uses: actions/cache/save@v4
      with:
        path: "/home/runner/.cache/bazel"
        key: ${{ runner.os }}-bazelcache

    - name: C++ Lint
      run: |
        bazel run :refresh_compile_commands
        CC_SOURCES=$(mktemp)
        find ./src -regextype egrep -regex ".*[.](cc|h)" -print0 > "$CC_SOURCES"
        export PATH="$(pwd)/external/toolchains_llvm++llvm+llvm_toolchain_llvm/bin":$PATH
        xargs --null clang-tidy < "$CC_SOURCES"
        xargs --null clang-format --dry-run -Werror -- < "$CC_SOURCES"
