name: clang-checks

on:
  push:
    branches:
    - main
    # For easier development without having to push to main.
    - workspace-configuration

  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest

    name: "Build/Test"

    steps:
    - name: Prepare
      run: |
        sudo apt-get update -qq
        curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash /dev/stdin 18

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Cache Timestamp
      id: cache_timestamp
      uses: nanzm/get-time-action@v1.1
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.cache/bazel"
        key: bazelcache_${{ steps.cache_timestamp.outputs.time }}
        restore-keys: bazelcache

    - name: Tests
      run: bazel test --test_output=errors //...
